/**
 * Lucide 语义图标注册表。
 *
 * 背景：Alice 的图标覆盖面很大，但生产 UI 需要保持单一几何体系，不能让每个组件临时挑一套图标。
 * 设计意图：把“图标长什么样”和“这个图标表达什么语义”分开；Playground、正式 UI 和后续替换都从这里发现候选。
 * 关键约束：生产只使用 lucide-react；注册表是语义目录，不复制 SVG 文件，也不承担页面布局或颜色决策。
 */

import type { LucideIcon } from 'lucide-react'
import {
  Activity,
  Archive,
  ArchiveRestore,
  ArrowLeft,
  ArrowRight,
  AtSign,
  BadgeCheck,
  Ban,
  BookOpen,
  Box,
  Braces,
  Bug,
  CalendarDays,
  Camera,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleUserRound,
  CircleX,
  Clock3,
  CloudSun,
  Coffee,
  Code2,
  Command,
  ContactRound,
  Copy,
  Database,
  Download,
  Dot,
  Eye,
  EyeOff,
  ExternalLink,
  File,
  FileCode2,
  FileJson,
  FileText,
  Fingerprint,
  FlaskConical,
  Flower2,
  Folder,
  FolderOpen,
  Forward,
  Gauge,
  Gift,
  GitBranch,
  Heart,
  History,
  Home,
  House,
  Image,
  Info,
  KeyRound,
  Keyboard,
  LayoutGrid,
  Link,
  Link2,
  List,
  ListTree,
  LoaderCircle,
  Lock,
  Logs,
  MapPin,
  Maximize2,
  MessageCircle,
  MessagesSquare,
  Mic,
  Minimize2,
  Music2,
  Minus,
  Moon,
  MoreHorizontal,
  MoreVertical,
  Network,
  Package,
  Paperclip,
  Palette,
  PanelLeft,
  PanelRight,
  PanelTop,
  Pause,
  Pencil,
  Pin,
  PinOff,
  Play,
  Plus,
  Redo2,
  RefreshCw,
  Reply,
  RotateCcw,
  Save,
  ScanSearch,
  Search,
  SearchCode,
  Send,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  SlidersHorizontal,
  Sparkles,
  Square,
  Sun,
  Table2,
  Terminal,
  TestTube2,
  Timer,
  Trash2,
  TriangleAlert,
  Undo2,
  Unlock,
  Upload,
  UserRound,
  UserRoundPlus,
  Users,
  Utensils,
  WandSparkles,
  Workflow,
  X,
  Zap,
} from 'lucide-react'

export type IconCategoryId = 'navigation' | 'conversation' | 'developer' | 'companion' | 'assets' | 'status'
export type IconPriority = 'P0' | 'P1'
export type IconAdoptionStatus = 'catalog' | 'adopted'

export interface IconCategoryDefinition {
  id: IconCategoryId
  label: string
  english: string
  description: string
}

export interface IconAssetDefinition {
  key: string
  category: IconCategoryId
  label: string
  english: string
  usage: string
  priority: IconPriority
  adoptionStatus: IconAdoptionStatus
  sourcePaths: readonly string[]
  icon: LucideIcon
}

export const ICON_CATEGORIES: readonly IconCategoryDefinition[] = [
  { id: 'navigation', label: '导航与操作', english: 'Navigation & Actions', description: '侧栏、搜索、页面切换和通用操作' },
  { id: 'conversation', label: '对话与生成', english: 'Conversation & Generation', description: '发送、生成、编辑、复制和消息状态' },
  { id: 'developer', label: '开发与实验', english: 'Developer & Experiments', description: 'Debug、Playground、Eval、工具和可观测' },
  { id: 'companion', label: '伙伴与生活', english: 'Companion & Life', description: '人物世界、朋友圈、资产和生活状态' },
  { id: 'assets', label: '文件与证据', english: 'Files & Evidence', description: 'Prompt、Skill、Memory、Provider 和权限证据' },
  { id: 'status', label: '状态与风险', english: 'Status & Risk', description: '成功、等待、警告、拒绝和风险等级' },
] as const

/** 只有能指向真实产品调用点的语义图标才标 adopted；其余只表示已进入候选目录。 */
export const ADOPTED_ICON_SOURCES: Readonly<Record<string, readonly string[]>> = {
  'navigation.menu': ['src/App.tsx'],
  'navigation.search': ['src/App.tsx', 'src/components/shell/PrimarySidebar.tsx'],
  'navigation.add': ['src/App.tsx', 'src/components/shell/PrimarySidebar.tsx'],
  'navigation.close': ['src/App.tsx', 'src/components/shell/PrimarySidebar.tsx'],
  'navigation.confirm': ['src/App.tsx'],
  'navigation.chevron-down': ['src/App.tsx'],
  'navigation.back': ['src/components/SettingsPanel.tsx'],
  'navigation.settings': ['src/components/shell/PrimarySidebar.tsx'],
  'conversation.send': ['src/App.tsx'],
  'conversation.stop': ['src/App.tsx'],
  'conversation.refresh': ['src/App.tsx'],
  'conversation.copy': ['src/App.tsx'],
  'conversation.edit': ['src/App.tsx'],
  'conversation.delete': ['src/App.tsx'],
  'conversation.pin': ['src/components/shell/PrimarySidebar.tsx'],
  'conversation.attachment': ['src/App.tsx'],
  'developer.debug': ['src/components/shell/PrimarySidebar.tsx'],
  'developer.playground': ['src/components/shell/PrimarySidebar.tsx'],
  'developer.activity': ['src/components/DevPanel.tsx'],
  'developer.test': ['src/components/DevPanel.tsx'],
  'companion.sparkles': ['src/components/shell/PrimarySidebar.tsx'],
  'assets.folder': ['src/App.tsx'],
  'assets.folder-open': ['src/App.tsx'],
  'assets.shield': ['src/App.tsx'],
  'status.blocked': ['src/App.tsx'],
  'status.energy': ['src/App.tsx'],
}

const icon = (category: IconCategoryId, key: string, label: string, english: string, usage: string, priority: IconPriority, component: LucideIcon): IconAssetDefinition => {
  const sourcePaths = ADOPTED_ICON_SOURCES[key] ?? []
  return {
    key,
    category,
    label,
    english,
    usage,
    priority,
    adoptionStatus: sourcePaths.length > 0 ? 'adopted' : 'catalog',
    sourcePaths,
    icon: component,
  }
}

export const ICON_ASSETS: readonly IconAssetDefinition[] = [
  // 导航与操作
  icon('navigation', 'navigation.menu', '菜单', 'Menu', '打开主导航', 'P0', PanelLeft),
  icon('navigation', 'navigation.panel-left', '左侧栏', 'Panel Left', '主导航 / 侧栏', 'P0', PanelLeft),
  icon('navigation', 'navigation.panel-right', '右侧栏', 'Panel Right', 'Debug / 辅助面板', 'P0', PanelRight),
  icon('navigation', 'navigation.search', '搜索', 'Search', '全局与局部搜索', 'P0', Search),
  icon('navigation', 'navigation.add', '新增', 'Plus', '新建会话 / 新增资产', 'P0', Plus),
  icon('navigation', 'navigation.remove', '移除', 'Minus', '收起 / 减少', 'P1', Minus),
  icon('navigation', 'navigation.close', '关闭', 'Close', '关闭面板 / 弹层', 'P0', X),
  icon('navigation', 'navigation.confirm', '确认', 'Check', '确认操作', 'P0', Check),
  icon('navigation', 'navigation.chevron-up', '展开向上', 'Chevron Up', '折叠控件', 'P1', ChevronUp),
  icon('navigation', 'navigation.chevron-down', '展开向下', 'Chevron Down', '折叠控件', 'P1', ChevronDown),
  icon('navigation', 'navigation.chevron-left', '向左', 'Chevron Left', '返回 / 上一项', 'P1', ChevronLeft),
  icon('navigation', 'navigation.chevron-right', '向右', 'Chevron Right', '下一项 / 进入', 'P1', ChevronRight),
  icon('navigation', 'navigation.back', '返回', 'Arrow Left', '返回上一层', 'P0', ArrowLeft),
  icon('navigation', 'navigation.forward', '前进', 'Arrow Right', '前进 / 跳转', 'P1', ArrowRight),
  icon('navigation', 'navigation.more-horizontal', '更多', 'More Horizontal', '行级菜单', 'P0', MoreHorizontal),
  icon('navigation', 'navigation.more-vertical', '更多操作', 'More Vertical', '上下文菜单', 'P0', MoreVertical),
  icon('navigation', 'navigation.settings', '设置', 'Settings', '系统设置入口', 'P0', Settings),
  icon('navigation', 'navigation.home', '首页', 'Home', '回到聊天 / 首页', 'P1', Home),
  icon('navigation', 'navigation.grid', '网格', 'Layout Grid', '模块或卡片网格', 'P1', LayoutGrid),
  icon('navigation', 'navigation.list', '列表', 'List', '列表视图', 'P1', List),
  icon('navigation', 'navigation.command', '命令', 'Command', '命令面板提示', 'P1', Command),
  icon('navigation', 'navigation.keyboard', '键盘', 'Keyboard', '快捷键说明', 'P1', Keyboard),
  icon('navigation', 'navigation.external-link', '外部链接', 'External Link', '打开外部文档', 'P1', ExternalLink),
  icon('navigation', 'navigation.maximize', '最大化', 'Maximize', '展开全屏', 'P1', Maximize2),
  icon('navigation', 'navigation.minimize', '最小化', 'Minimize', '退出全屏', 'P1', Minimize2),

  // 对话与生成
  icon('conversation', 'conversation.send', '发送', 'Send', '提交当前消息', 'P0', Send),
  icon('conversation', 'conversation.stop', '停止生成', 'Stop', '停止流式生成', 'P0', Square),
  icon('conversation', 'conversation.generating', '生成中', 'Generating', '流式生成状态', 'P0', LoaderCircle),
  icon('conversation', 'conversation.refresh', '重新生成', 'Regenerate', '重新生成回复', 'P0', RefreshCw),
  icon('conversation', 'conversation.retry', '重试', 'Retry', '失败后重试', 'P0', RotateCcw),
  icon('conversation', 'conversation.copy', '复制', 'Copy', '复制文本或证据', 'P0', Copy),
  icon('conversation', 'conversation.copied', '已复制', 'Copied', '复制完成反馈', 'P0', CheckCheck),
  icon('conversation', 'conversation.edit', '编辑', 'Edit', '编辑消息 / 资产草稿', 'P0', Pencil),
  icon('conversation', 'conversation.delete', '删除', 'Delete', '删除草稿或记录', 'P1', Trash2),
  icon('conversation', 'conversation.undo', '撤销', 'Undo', '撤销本地编辑', 'P1', Undo2),
  icon('conversation', 'conversation.redo', '重做', 'Redo', '恢复本地编辑', 'P1', Redo2),
  icon('conversation', 'conversation.pin', '置顶', 'Pin', '置顶会话或记录', 'P1', Pin),
  icon('conversation', 'conversation.unpin', '取消置顶', 'Unpin', '取消置顶', 'P1', PinOff),
  icon('conversation', 'conversation.message', '消息', 'Message', '单条消息入口', 'P0', MessageCircle),
  icon('conversation', 'conversation.messages', '多轮对话', 'Messages', '会话列表 / 多轮上下文', 'P0', MessagesSquare),
  icon('conversation', 'conversation.reply', '回复', 'Reply', '引用或回复', 'P1', Reply),
  icon('conversation', 'conversation.forward', '转发', 'Forward', '转发或派发', 'P1', Forward),
  icon('conversation', 'conversation.attachment', '附件', 'Attachment', '附加文件', 'P1', Paperclip),
  icon('conversation', 'conversation.mention', '提及', 'Mention', '提及角色 / 工具', 'P1', AtSign),
  icon('conversation', 'conversation.voice', '语音', 'Voice', '未来语音输入入口预留', 'P1', Mic),

  // 开发与实验
  icon('developer', 'developer.debug', '调试', 'Debug', '生产事实与运行追踪', 'P0', Bug),
  icon('developer', 'developer.playground', '实验场', 'Playground', '隔离 UI / 对话实验', 'P0', FlaskConical),
  icon('developer', 'developer.terminal', '终端', 'Terminal', '命令控制台 / 工具执行', 'P0', Terminal),
  icon('developer', 'developer.code', '代码', 'Code', '代码或 Prompt 结构', 'P0', Code2),
  icon('developer', 'developer.braces', '结构', 'Braces', 'JSON / schema / 结构化资产', 'P1', Braces),
  icon('developer', 'developer.file-code', '代码文件', 'File Code', '源文件证据', 'P1', FileCode2),
  icon('developer', 'developer.database', '数据库', 'Database', '存储与查询', 'P0', Database),
  icon('developer', 'developer.network', '网络', 'Network', 'Provider / MCP / 网络状态', 'P0', Network),
  icon('developer', 'developer.activity', '活动', 'Activity', '事件流与运行活动', 'P0', Activity),
  icon('developer', 'developer.workflow', '工作流', 'Workflow', '任务链 / 调度', 'P1', Workflow),
  icon('developer', 'developer.branch', '分支', 'Git Branch', '会话分支 / 版本分叉', 'P1', GitBranch),
  icon('developer', 'developer.package', '资产包', 'Package', 'Role Pack / Skill Pack', 'P0', Package),
  icon('developer', 'developer.box', '容器', 'Box', '隔离草稿 / 资产容器', 'P1', Box),
  icon('developer', 'developer.search-code', '搜索代码', 'Search Code', '代码与 Prompt 搜索', 'P1', SearchCode),
  icon('developer', 'developer.scan', '扫描', 'Scan Search', '审计 / 扫描结果', 'P1', ScanSearch),
  icon('developer', 'developer.eye', '查看', 'Eye', '显示证据或正文', 'P0', Eye),
  icon('developer', 'developer.eye-off', '隐藏', 'Eye Off', '隐藏敏感字段', 'P0', EyeOff),
  icon('developer', 'developer.logs', '日志', 'Logs', '运行记录 / 事件日志', 'P0', Logs),
  icon('developer', 'developer.tree', '树状结构', 'List Tree', '调用链 / 资产关系', 'P1', ListTree),
  icon('developer', 'developer.panel-top', '顶部面板', 'Panel Top', '开发者辅助面板', 'P1', PanelTop),
  icon('developer', 'developer.table', '表格', 'Table', '注册表 / Eval 结果', 'P1', Table2),
  icon('developer', 'developer.sliders', '参数', 'Sliders', '模型 / 试验参数', 'P0', SlidersHorizontal),
  icon('developer', 'developer.wand', '魔杖', 'Wand Sparkles', '生成辅助 / 试验操作', 'P1', WandSparkles),
  icon('developer', 'developer.test', '测试', 'Test', 'Eval / 单元测试', 'P0', TestTube2),
  icon('developer', 'developer.play', '运行', 'Play', '运行试验或测试', 'P0', Play),
  icon('developer', 'developer.pause', '暂停', 'Pause', '暂停后台试验', 'P1', Pause),

  // 伙伴与生活
  icon('companion', 'companion.heart', '关系', 'Heart', '关系感 / 关注', 'P0', Heart),
  icon('companion', 'companion.sparkles', '灵感', 'Sparkles', '伙伴回应 / 新发现', 'P0', Sparkles),
  icon('companion', 'companion.sun', '白天', 'Sun', '白天 / 活跃状态', 'P1', Sun),
  icon('companion', 'companion.moon', '夜晚', 'Moon', '夜晚 / 安静状态', 'P1', Moon),
  icon('companion', 'companion.weather', '天气', 'Cloud Sun', '生活世界天气', 'P1', CloudSun),
  icon('companion', 'companion.calendar', '日历', 'Calendar Days', '日期 / 事件', 'P0', CalendarDays),
  icon('companion', 'companion.clock', '时间', 'Clock', '时间 / 最近活动', 'P0', Clock3),
  icon('companion', 'companion.location', '地点', 'Map Pin', '位置 / 场景', 'P0', MapPin),
  icon('companion', 'companion.home', '住所', 'House', '住所 / 生活空间', 'P0', House),
  icon('companion', 'companion.book', '故事', 'Book Open', '人物故事 / 日记', 'P0', BookOpen),
  icon('companion', 'companion.coffee', '日常', 'Coffee', '日常活动', 'P1', Coffee),
  icon('companion', 'companion.food', '饮食', 'Utensils', '生活事件 / 饮食', 'P1', Utensils),
  icon('companion', 'companion.music', '音乐', 'Music', '生活氛围 / 活动', 'P1', Music2),
  icon('companion', 'companion.camera', '朋友圈', 'Camera', 'Moments / 记录', 'P0', Camera),
  icon('companion', 'companion.image', '图片', 'Image', '图片资产 / 视觉', 'P1', Image),
  icon('companion', 'companion.palette', '审美', 'Palette', '主题 / 视觉实验', 'P1', Palette),
  icon('companion', 'companion.flower', '花草', 'Flower 2', '生活世界装饰语义', 'P1', Flower2),
  icon('companion', 'companion.people', '名册', 'Users', '朋友圈 / 关系网', 'P0', Users),
  icon('companion', 'companion.person', '人物', 'User Round', '角色卡 / 当前伙伴', 'P0', UserRound),
  icon('companion', 'companion.add-person', '召唤', 'User Round Plus', '召唤 / 新角色', 'P0', UserRoundPlus),
  icon('companion', 'companion.cast', '角色架', 'Contact Round', '角色架 / 卡司', 'P0', ContactRound),
  icon('companion', 'companion.wardrobe', '衣柜', 'Shirt', '衣柜 / 穿搭资产', 'P0', Shirt),
  icon('companion', 'companion.shopping', '购物袋', 'Shopping Bag', '资产 / 物品', 'P1', ShoppingBag),
  icon('companion', 'companion.gift', '礼物', 'Gift', '关系事件 / 赠礼', 'P1', Gift),
  icon('companion', 'companion.identity', '身份', 'Circle User Round', '人物身份摘要', 'P0', CircleUserRound),

  // 文件与证据
  icon('assets', 'assets.file', '文件', 'File', '通用文件资产', 'P0', File),
  icon('assets', 'assets.text-file', '文本文件', 'File Text', 'Prompt / 文档', 'P0', FileText),
  icon('assets', 'assets.json-file', 'JSON 文件', 'File JSON', '结构化资产', 'P0', FileJson),
  icon('assets', 'assets.folder', '文件夹', 'Folder', '资产目录', 'P0', Folder),
  icon('assets', 'assets.folder-open', '打开文件夹', 'Folder Open', '浏览目录', 'P1', FolderOpen),
  icon('assets', 'assets.upload', '导入', 'Upload', '导入草稿 / 数据', 'P0', Upload),
  icon('assets', 'assets.download', '导出', 'Download', '导出证据 / 数据', 'P0', Download),
  icon('assets', 'assets.save', '保存', 'Save', '保存隔离草稿', 'P0', Save),
  icon('assets', 'assets.archive', '归档', 'Archive', '归档记录 / 版本', 'P1', Archive),
  icon('assets', 'assets.restore', '恢复', 'Archive Restore', '从归档恢复', 'P1', ArchiveRestore),
  icon('assets', 'assets.history', '历史', 'History', '查看版本与运行记录', 'P0', History),
  icon('assets', 'assets.link', '链接', 'Link', '关联资产 / 来源', 'P1', Link),
  icon('assets', 'assets.link-2', '关联', 'Link 2', '反向查询 / 依赖关系', 'P1', Link2),
  icon('assets', 'assets.lock', '锁定', 'Lock', 'PROTECTED / 只读', 'P0', Lock),
  icon('assets', 'assets.unlock', '解锁', 'Unlock', '可编辑 / 解锁', 'P1', Unlock),
  icon('assets', 'assets.shield', '防护', 'Shield', '安全边界', 'P0', Shield),
  icon('assets', 'assets.key', '密钥', 'Key Round', '凭据状态（不展示原文）', 'P0', KeyRound),
  icon('assets', 'assets.fingerprint', '指纹', 'Fingerprint', '资产指纹 / 证据一致性', 'P1', Fingerprint),

  // 状态与风险
  icon('status', 'status.info', '信息', 'Info', '补充说明', 'P0', Info),
  icon('status', 'status.help', '帮助', 'Circle Help', '帮助 / 解释', 'P1', CircleHelp),
  icon('status', 'status.success', '成功', 'Circle Check', '操作成功', 'P0', CircleCheck),
  icon('status', 'status.failure', '失败', 'Circle X', '操作失败', 'P0', CircleX),
  icon('status', 'status.warning', '警告', 'Circle Alert', '需要注意', 'P0', CircleAlert),
  icon('status', 'status.danger', '危险', 'Triangle Alert', '高风险 / 阻止', 'P0', TriangleAlert),
  icon('status', 'status.approved', '已批准', 'Badge Check', '已采用 / 已验证', 'P1', BadgeCheck),
  icon('status', 'status.secure', '安全', 'Shield Check', '通过安全检查', 'P0', ShieldCheck),
  icon('status', 'status.security-alert', '安全警告', 'Shield Alert', '需要安全复核', 'P0', ShieldAlert),
  icon('status', 'status.blocked', '已阻止', 'Ban', '权限拒绝 / 禁止', 'P0', Ban),
  icon('status', 'status.idle', '空闲', 'Circle', '未运行 / 空闲', 'P1', Circle),
  icon('status', 'status.dot', '指示点', 'Dot', '弱状态指示', 'P1', Dot),
  icon('status', 'status.energy', '活跃', 'Zap', '活跃 / 即时反馈', 'P1', Zap),
  icon('status', 'status.gauge', '资源', 'Gauge', '用量 / 性能', 'P1', Gauge),
  icon('status', 'status.timer', '计时', 'Timer', '等待 / 超时', 'P0', Timer),
] as const

export type IconKey = (typeof ICON_ASSETS)[number]['key']

export const ICON_REGISTRY = Object.fromEntries(
  ICON_ASSETS.map((asset) => [asset.key, asset]),
) as Record<IconKey, IconAssetDefinition>

export function getIconAsset(key: IconKey): IconAssetDefinition {
  return ICON_REGISTRY[key]
}
