import { test, expect } from '@playwright/test'

for (const theme of ['porcelain-blue', 'yao-stone']) for (const width of [1096, 600]) {
  test(`正式侧栏与输入边界 ${theme} ${width}`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 704 })
    await page.addInitScript(theme => localStorage.setItem('theme', theme), theme)
    await page.goto('/')
    const sidebar = page.getByTestId('primary-sidebar')
    const composer = page.getByTestId('chat-composer')
    const message = page.getByRole('textbox', { name: '消息', exact: true })
    await message.fill('边界检查')
    await expect(message).toHaveCSS('border-top-width', '0px')
    await expect(message).toHaveCSS('box-shadow', 'none')
    await expect(composer).toHaveCSS('border-top-width', '1px')
    await expect(composer).toHaveCSS('outline-width', '1px')
    await page.screenshot({ path: info.outputPath('composer-focus.png') })
    await sidebar.getByRole('button', { name: '搜索会话', exact: true }).click()
    const search = sidebar.getByTestId('sidebar-session-search')
    await search.fill('不存在的会话')
    await expect(search).toHaveCSS('border-top-width', '0px')
    await expect(search).toHaveCSS('box-shadow', 'none')
    await expect(search.locator('..')).toHaveCSS('border-top-width', '1px')
    await expect(search.locator('..')).toHaveCSS('outline-width', '1px')
    await page.screenshot({ path: info.outputPath('search-focus.png') })
    await search.press('Escape')
    await expect(search).toHaveCount(0)
    await expect(sidebar.getByRole('button', { name: '新对话', exact: true })).toBeVisible()
    await expect(message).toHaveValue('边界检查')
    const dock = sidebar.getByRole('button', { name: '人物世界', exact: true }).locator('..').locator('..')
    await expect(dock).toHaveCSS('border-top-width', '0px')
    await sidebar.getByRole('button', { name: '人物世界', exact: true }).click()
    await expect(page.getByTestId('world-hub')).toBeVisible()
  })
}
