import { test, expect } from '@playwright/test'

for (const theme of ['porcelain-blue', 'yao-stone']) for (const width of [1096, 600]) {
  test(`通讯录人物与经历 ${theme} ${width}`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 704 })
    await page.addInitScript(theme => localStorage.setItem('theme', theme), theme)
    await page.goto('/')
    await page.getByTestId('primary-sidebar').getByRole('button', { name: 'Playground', exact: true }).click()
    await page.getByTestId('playground-nav').getByRole('button', { name: '人物世界', exact: true }).click()
    await page.getByTestId('world-tab-cast').click()
    const panel = page.getByTestId('world-cast-fixture')
    const scenario = panel.getByRole('tablist', { name: '通讯录状态样张' })
    const card = panel.getByTestId('contact-card-yao')
    await expect(card).toHaveCSS('border-radius', '16px')
    const box = await card.boundingBox()
    await card.hover()
    await card.focus()
    expect(await card.boundingBox()).toEqual(box)
    const other = await panel.getByTestId('contact-card-xu').boundingBox()
    expect(width === 600 ? other!.y > box!.y : Math.abs(other!.y - box!.y) < 2).toBe(true)
    await page.screenshot({ path: info.outputPath('contacts-list.png') })
    await card.press('Enter')
    await expect(panel.getByTestId('contact-detail')).toContainText('一本书，两种读法')
    await panel.getByRole('button', { name: '查看旅行记录' }).click()
    await expect(panel.getByTestId('contact-detail')).toContainText('这次没有把行程排满。')
    await panel.getByRole('button', { name: '返回', exact: true }).click()
    await expect(panel.getByRole('button', { name: '查看旅行记录' })).toBeFocused()
    await page.screenshot({ path: info.outputPath('contacts-detail.png') })
    await panel.getByRole('button', { name: '返回', exact: true }).click()
    await expect(card).toBeFocused()
    await scenario.getByRole('tab', { name: '长姓名' }).click()
    await expect(card).toContainText('完整显示')
    expect(await panel.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    await scenario.getByRole('tab', { name: '无共同经历' }).click()
    await card.click()
    await expect(panel).toContainText('还没有留下共同经历')
    await expect(panel.getByRole('button', { name: '查看旅行记录' })).toHaveCount(0)
    await scenario.getByRole('tab', { name: '头像失败' }).click()
    await expect(card.locator('img')).toHaveCount(0)
    await scenario.getByRole('tab', { name: '空通讯录' }).click()
    await expect(panel).toContainText('还没有认识的人')
    await expect(panel.getByRole('button', { name: '开聊' })).toHaveCount(0)
  })
}
