import { test, expect } from '@playwright/test'

for (const theme of ['porcelain-blue', 'yao-stone']) for (const width of [1096, 746]) {
  test(`设计语言布局与透明度 ${theme} ${width}`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 704 })
    await page.addInitScript(theme => localStorage.setItem('theme', theme), theme)
    await page.goto('/')
    await page.getByTestId('primary-sidebar').getByRole('button', { name: 'Playground', exact: true }).click()
    await page.getByTestId('playground-nav').getByRole('button', { name: '设计语言', exact: true }).click()
    const tabs = page.getByRole('tablist', { name: '设计语言分类' })
    await tabs.getByRole('tab', { name: '布局与间距' }).click()
    const reading = page.getByTestId('layout-reading')
    const back = page.getByTestId('layout-back')
    expect(Math.abs((await reading.boundingBox())!.x - (await back.boundingBox())!.x)).toBeLessThanOrEqual(2)
    const media = page.getByTestId('layout-media')
    const dimensions = await media.boundingBox()
    await page.getByRole('tab', { name: '加载中', exact: true }).click()
    expect(await media.boundingBox()).toEqual(dimensions)
    await page.getByRole('tab', { name: '加载失败', exact: true }).click()
    expect(await media.boundingBox()).toEqual(dimensions)
    await page.getByRole('button', { name: '长正文', exact: true }).click()
    expect(await page.getByTestId('layout-scroll-sample').evaluate(node => node.scrollHeight > node.clientHeight)).toBe(true)
    const row = page.getByTestId('layout-hover-row')
    await row.scrollIntoViewIfNeeded()
    await page.mouse.move(0, 0)
    const before = await row.boundingBox()
    const action = page.getByTestId('layout-hover-action')
    const actionBefore = await action.boundingBox()
    await row.hover()
    expect(await row.boundingBox()).toEqual(before)
    expect(await action.boundingBox()).toEqual(actionBefore)
    await expect(action).toHaveCSS('opacity', '1')
    await back.click()
    await page.getByRole('button', { name: '查看旅行', exact: true }).click()
    await expect(reading).toBeVisible()
    await page.screenshot({ path: info.outputPath('layout.png'), fullPage: true })
    await tabs.getByRole('tab', { name: '透明度', exact: true }).click()
    const surface = page.getByTestId('opacity-surface')
    const initial = await surface.evaluate(node => getComputedStyle(node).backgroundColor)
    await page.getByRole('button', { name: '80%', exact: true }).click()
    await expect(page.locator('output')).toHaveText('80%')
    expect(await surface.evaluate(node => getComputedStyle(node).backgroundColor)).not.toBe(initial)
    await page.getByRole('slider', { name: '表面透明度' }).focus()
    await page.keyboard.press('ArrowLeft')
    await expect(page.locator('output')).toHaveText('75%')
    await expect(surface).toHaveCSS('opacity', '1')
    await page.screenshot({ path: info.outputPath('opacity.png'), fullPage: true })
    await page.getByTestId('design-system-panel').evaluate(node => { (node as HTMLElement).style.zoom = '2' })
    expect(await page.getByTestId('design-system-panel').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    await tabs.getByRole('tab', { name: '透明度', exact: true }).focus()
    await page.keyboard.press('ArrowLeft')
    await expect(tabs.getByRole('tab', { name: '布局与间距' })).toHaveAttribute('aria-selected', 'true')
  })
}
