import { test, expect } from '@playwright/test'

for (const theme of ['porcelain-blue', 'yao-stone']) for (const width of [1096, 746]) {
  test(`输入边界候选 ${theme} ${width}`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 704 })
    await page.addInitScript(theme => localStorage.setItem('theme', theme), theme)
    await page.goto('/')
    await page.getByTestId('primary-sidebar').getByRole('button', { name: 'Playground', exact: true }).click()
    const nav = page.getByTestId('playground-nav')
    await expect(page.getByTestId('playground-product-nav')).toHaveCount(0)
    await expect(nav.getByText('产品入口', { exact: true })).toHaveCount(0)
    await nav.getByRole('button', { name: '人物世界', exact: true }).click()
    await expect(page.getByTestId('world-tab-wardrobe')).toBeVisible()
    await nav.getByRole('button', { name: '设置', exact: true }).click()
    await expect(page.getByTestId('settings-main')).toBeVisible()
    await nav.getByRole('button', { name: '基础组件', exact: true }).click()
    await page.getByRole('tab', { name: '按钮', exact: true }).click()
    for (const selector of ['.foundation-action-button', '.foundation-button']) {
      const button = page.locator(selector).filter({ visible: true }).first()
      await button.scrollIntoViewIfNeeded()
      await expect(button).toHaveCSS('border-radius', '6px')
      const before = await button.boundingBox()
      await button.hover()
      await button.focus()
      expect(await button.boundingBox()).toEqual(before)
    }
    await expect(page.locator('.playground-story-block').first()).toHaveCSS('border-radius', '16px')
    await page.getByRole('tab', { name: '卡片', exact: true }).click()
    for (const card of await page.locator('[data-shape="card"]').all()) await expect(card).toHaveCSS('border-radius', '16px')
    await page.getByRole('tab', { name: '弹层', exact: true }).click()
    await page.getByRole('button', { name: '打开对话框', exact: true }).click()
    await expect(page.getByRole('dialog', { name: '确认清理样张' })).toHaveCSS('border-radius', '22px')
    await page.getByRole('button', { name: '关闭对话框', exact: true }).click()
    await page.getByRole('tab', { name: '输入与表单', exact: true }).click()
    const fields = ['基础输入默认', '超长内容输入', '带图标输入', '显示名称', '错误字段']
    for (const name of fields) {
      const scope = ['显示名称', '错误字段'].includes(name) ? page.getByTestId('foundation-story-form-field') : page
      const field = scope.getByRole('textbox', { name, exact: true })
      await field.scrollIntoViewIfNeeded()
      await field.blur()
      const radius = await field.evaluate(node => getComputedStyle(node).getPropertyValue('--radius-md').trim())
      await expect(field).toHaveCSS('border-top-width', '1px')
      await expect(field).toHaveCSS('border-top-left-radius', radius)
      const before = await field.boundingBox()
      await field.hover()
      expect(await field.boundingBox()).toEqual(before)
      await field.focus()
      await expect(field).toHaveCSS('box-shadow', 'none')
      expect(await field.boundingBox()).toEqual(before)
      await field.fill('测试输入')
      await expect(field).toHaveValue('测试输入')
      await field.evaluate(node => (node as HTMLInputElement).disabled = true)
      expect(await field.boundingBox()).toEqual(before)
      await field.evaluate(node => (node as HTMLInputElement).disabled = false)
    }
    const form = page.getByTestId('foundation-story-form-field')
    const error = form.getByRole('textbox', { name: '错误字段', exact: true })
    await error.blur()
    const errorColor = await error.evaluate(node => getComputedStyle(node).borderColor)
    await error.focus()
    await expect(error).toHaveCSS('border-color', errorColor)
    expect(errorColor).not.toBe(await form.getByRole('textbox', { name: '显示名称', exact: true }).evaluate(node => getComputedStyle(node).borderColor))
    await error.evaluate(node => (node as HTMLElement).style.setProperty('--radius-input', '14px'))
    await expect(error).toHaveCSS('border-radius', '14px')
    await error.evaluate(node => (node as HTMLElement).style.removeProperty('--radius-input'))
    await page.screenshot({ path: info.outputPath('input-fields.png'), fullPage: true })
    await page.getByRole('tab', { name: '标签与选择', exact: true }).click()
    await expect(page.getByRole('combobox', { name: '搜索伙伴' })).toHaveCSS('border-top-width', '1px')
    await page.getByRole('tab', { name: '菜单与提示', exact: true }).click()
    const embedded = page.getByRole('textbox', { name: '搜索动作', exact: true })
    await embedded.scrollIntoViewIfNeeded()
    await embedded.focus()
    await expect(embedded).toHaveCSS('border-top-width', '0px')
    await expect(embedded).toHaveCSS('box-shadow', 'none')
    await embedded.fill('打开')
    await expect(embedded).toHaveValue('打开')
    expect(await page.getByTestId('playground-main').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    await nav.getByRole('button', { name: '返回', exact: true }).click()
    await expect(page.getByTestId('primary-sidebar')).toBeVisible()
  })
}

for (const width of [640, 1096]) test(`产品体验共享间距 ${width}`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 704 })
  await page.goto('/')
  await page.getByTestId('primary-sidebar').getByRole('button', { name: 'Playground', exact: true }).click()
  const nav = page.getByTestId('playground-nav')
  await nav.getByRole('button', { name: 'Chat', exact: true }).click()
  const chat = page.getByTestId('surface-baseline-panel')
  const messages = page.getByTestId('chat-surface-scroll')
  const composer = page.getByTestId('chat-surface-composer-area')
  await expect(messages).toHaveCSS('padding-left', '24px')
  await expect(composer).toHaveCSS('padding-left', '24px')
  await chat.evaluate(node => (node as HTMLElement).style.setProperty('--layout-gutter-large', '31px'))
  await expect(messages).toHaveCSS('padding-left', '31px')
  await expect(composer).toHaveCSS('padding-left', '31px')
  await chat.evaluate(node => (node as HTMLElement).style.removeProperty('--layout-gutter-large'))
  await nav.getByRole('button', { name: '设置', exact: true }).click()
  await expect(page.getByTestId('settings-main')).toHaveCSS('padding-left', '24px')
  const card = page.locator('[data-layout-card="settings"]').first()
  await expect(card).toHaveCSS('padding-left', '20px')
  await page.getByTestId('settings-candidate').evaluate(node => (node as HTMLElement).style.setProperty('--layout-card-large', '29px'))
  await expect(card).toHaveCSS('padding-left', '29px')
  await nav.getByRole('button', { name: '人物世界', exact: true }).click()
  await expect(page.getByTestId('moments-content-scroll')).toHaveCSS('padding-left', '16px')
  await page.getByTestId('world-tab-wardrobe').click()
  await expect(page.getByTestId('wardrobe-content-scroll')).toHaveCSS('padding-left', '16px')
  await page.screenshot({ path: info.outputPath('product-spacing.png'), fullPage: true })
  await nav.getByRole('button', { name: '工作区', exact: true }).click()
  const workspaceTabs = page.getByRole('tablist', { name: '工作区功能' })
  await workspaceTabs.getByRole('tab', { name: '终端', exact: true }).click()
  await expect(page.getByTestId('workspace-terminal-output')).toHaveCSS('padding-left', '16px')
  await workspaceTabs.getByRole('tab', { name: '侧边聊天', exact: true }).click()
  await expect(page.getByTestId('workspace-sidechat-messages')).toHaveCSS('padding-left', '16px')
})

for (const theme of ['porcelain-blue', 'yao-stone']) for (const width of [1096, 746]) {
  test(`设计语言布局与透明度 ${theme} ${width}`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 704 })
    await page.addInitScript(theme => localStorage.setItem('theme', theme), theme)
    await page.goto('/')
    await page.getByTestId('primary-sidebar').getByRole('button', { name: 'Playground', exact: true }).click()
    await page.getByTestId('playground-nav').getByRole('button', { name: '设计语言', exact: true }).click()
    const tabs = page.getByRole('tablist', { name: '设计语言分类' })
    const tabFrame = tabs.locator('[role="presentation"]').first()
    await expect(tabFrame).toHaveCSS('border-top-width', '1px')
    await expect(tabFrame).toHaveCSS('border-radius', '6px')
    const tabBounds = await tabFrame.boundingBox()
    await tabFrame.hover()
    await tabs.getByRole('tab').first().focus()
    expect(await tabFrame.boundingBox()).toEqual(tabBounds)
    await tabs.getByRole('tab').nth(1).click()
    expect(await tabFrame.boundingBox()).toEqual(tabBounds)
    await tabs.getByRole('tab', { name: '布局与间距' }).click()
    const samples = page.getByTestId('layout-language-samples')
    await expect(page.getByRole('button', { name: '重置布局参数', exact: true })).toHaveCSS('border-radius', '6px')
    const densityTabs = page.getByRole('tablist', { name: '布局密度' })
    await expect(densityTabs.getByRole('tab')).toHaveText(['紧凑', '标准', '宽松'])
    await expect(samples.getByRole('heading', { level: 3 })).toHaveText(['文字', '图片', '图文组合', '模块', '边界与对齐'])
    await expect(samples.getByRole('heading', { name: '独立布局契约' })).toHaveCount(0)
    await expect(samples.getByRole('heading', { name: '布局稳定性' })).toHaveCount(0)
    for (const [label, gutter, section] of [['紧凑', 12, 12], ['标准', 16, 20], ['宽松', 24, 24]] as const) {
      await densityTabs.getByRole('tab', { name: label, exact: true }).click()
      await expect(page.getByTestId('layout-align-left')).toHaveCSS('padding-left', `${gutter}px`)
      await expect(page.getByTestId('layout-module-grid')).toHaveCSS('gap', `${section}px`)
      await expect(page.getByTestId('layout-module-single')).toHaveCSS('padding-left', `${gutter}px`)
      for (const card of await page.getByTestId('layout-module-card').all()) await expect(card).toHaveCSS('padding-left', `${gutter}px`)
      expect(await samples.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    }
    await densityTabs.getByRole('tab', { name: '标准', exact: true }).click()
    for (const heading of await samples.getByRole('heading', { level: 3 }).all()) await expect(heading).toHaveCSS('font-weight', '700')
    for (const example of await samples.locator('[data-testid="layout-section-text"] .border, [data-testid="layout-section-images"] figure, [data-testid="layout-section-combinations"] > div > .border').all()) await expect(example).toHaveCSS('border-top-width', '1px')
    const gutterInput = page.getByRole('spinbutton', { name: '页面边距数值', exact: true })
    await gutterInput.fill('31')
    await expect(page.getByRole('slider', { name: '页面边距', exact: true })).toHaveValue('31')
    await expect(page.getByTestId('layout-preview-gutter')).toHaveCSS('padding-left', '31px')
    await expect(page.getByTestId('layout-custom-label')).toHaveText('自定义')
    await gutterInput.fill('')
    await gutterInput.blur()
    await expect(gutterInput).toHaveValue('31')
    await gutterInput.fill('999')
    await gutterInput.press('Enter')
    await expect(gutterInput).toHaveValue('48')
    await gutterInput.fill('-5')
    await gutterInput.blur()
    await expect(gutterInput).toHaveValue('0')
    for (const [label, value, target, property] of [
      ['内容宽度', 400, 'layout-preview-width', 'max-width'],
      ['区块间距', 33, 'layout-module-grid', 'gap'],
      ['卡片内边距', 27, 'layout-module-single', 'padding-left'],
    ] as const) {
      const input = page.getByRole('spinbutton', { name: `${label}数值`, exact: true })
      await input.fill(String(value))
      await input.press('Enter')
      await expect(page.getByTestId(target)).toHaveCSS(property, `${value}px`)
      const slider = page.getByRole('slider', { name: label, exact: true })
      await expect(slider).toHaveValue(String(value))
      await slider.focus()
      await slider.press('ArrowRight')
      await expect(input).toHaveValue(String(value + 1))
    }
    await page.getByRole('spinbutton', { name: '内容宽度数值' }).fill('240')
    await page.getByRole('spinbutton', { name: '卡片内边距数值' }).fill('48')
    expect(await samples.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    for (const sample of await samples.locator('section').all()) expect(await sample.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    await page.getByRole('button', { name: '重置布局参数', exact: true }).click()
    await expect(gutterInput).toHaveValue('16')
    await expect(page.getByRole('spinbutton', { name: '内容宽度数值' })).toHaveValue('672')
    await expect(page.getByRole('spinbutton', { name: '区块间距数值' })).toHaveValue('20')
    await expect(page.getByRole('spinbutton', { name: '卡片内边距数值' })).toHaveValue('16')
    await expect(page.getByTestId('layout-custom-label')).toHaveText('')
    await expect(densityTabs.getByRole('tab', { name: '标准', exact: true })).toHaveAttribute('aria-selected', 'true')
    for (const [index, ratio] of [3 / 2, 2 / 3, 1].entries()) {
      const media = page.getByTestId('layout-ratio-image').nth(index)
      expect(await media.evaluate(node => (node as HTMLImageElement).complete && (node as HTMLImageElement).naturalWidth > 0)).toBe(true)
      const box = (await media.boundingBox())!
      expect(Math.abs(box.width / box.height - ratio)).toBeLessThan(0.01)
    }
    for (const sample of await samples.locator('section').all()) {
      await expect(sample).toHaveCSS('overflow-y', 'visible')
      expect(await sample.evaluate(node => node.scrollHeight - node.clientHeight)).toBeLessThanOrEqual(1)
    }
    const left = (await page.getByTestId('layout-align-left').boundingBox())!
    const readingLeft = (await page.getByTestId('layout-reading-left').boundingBox())!
    expect(Math.abs(readingLeft.x - left.x - 17)).toBeLessThanOrEqual(2)
    const center = (await page.getByTestId('layout-align-center').boundingBox())!
    const readingCenter = (await page.getByTestId('layout-reading-center').boundingBox())!
    expect(Math.abs(readingCenter.x + readingCenter.width / 2 - center.x - center.width / 2)).toBeLessThanOrEqual(2)
    const row = page.getByTestId('layout-module-action-row')
    await row.scrollIntoViewIfNeeded()
    await page.mouse.move(0, 0)
    const before = await row.boundingBox()
    const action = page.getByTestId('layout-module-action')
    const actionBefore = await action.boundingBox()
    await row.hover()
    expect(await row.boundingBox()).toEqual(before)
    expect(await action.boundingBox()).toEqual(actionBefore)
    await expect(action).toHaveCSS('opacity', '1')
    await page.context().grantPermissions(['clipboard-read', 'clipboard-write'])
    await action.click()
    await expect(samples.getByRole('status')).toHaveText('已复制')
    expect(await row.boundingBox()).toEqual(before)
    expect(await action.boundingBox()).toEqual(actionBefore)
    expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('午后的光映在水面上')
    await page.evaluate(() => { Object.defineProperty(navigator.clipboard, 'writeText', { configurable: true, value: async () => { throw new Error('fixture denied') } }) })
    await action.click()
    await expect(samples.getByRole('status')).toHaveText('复制未成功，请重试。')
    expect(await row.boundingBox()).toEqual(before)
    await densityTabs.scrollIntoViewIfNeeded()
    await page.screenshot({ path: info.outputPath('layout.png'), fullPage: true })
    await tabs.getByRole('tab', { name: '透明度', exact: true }).click()
    const surface = page.getByTestId('opacity-surface')
    const initial = await surface.evaluate(node => getComputedStyle(node).backgroundColor)
    const textSurface = page.getByTestId('opacity-text-surface')
    await expect(textSurface).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
    await expect(page.getByRole('heading', { name: '表面透明度', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: '80%', exact: true }).click()
    await expect(page.locator('output')).toHaveText('80%')
    expect(await surface.evaluate(node => getComputedStyle(node).backgroundColor)).not.toBe(initial)
    await expect(textSurface).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
    await expect(textSurface).toHaveCSS('opacity', '1')
    await page.getByRole('slider', { name: '表面透明度' }).focus()
    await page.keyboard.press('ArrowLeft')
    await expect(page.locator('output')).toHaveText('75%')
    await expect(textSurface).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
    await expect(surface).toHaveCSS('opacity', '1')
    await page.screenshot({ path: info.outputPath('opacity.png'), fullPage: true })
    await page.getByTestId('design-system-panel').evaluate(node => { (node as HTMLElement).style.zoom = '2' })
    expect(await page.getByTestId('design-system-panel').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    await tabs.getByRole('tab', { name: '透明度', exact: true }).focus()
    await page.keyboard.press('ArrowLeft')
    await expect(tabs.getByRole('tab', { name: '布局与间距' })).toHaveAttribute('aria-selected', 'true')
    await page.getByTestId('design-system-panel').evaluate(node => { (node as HTMLElement).style.zoom = '1' })
    await tabs.getByRole('tab', { name: '形态与动效', exact: true }).click()
    const roles = page.getByTestId('radius-role-grid').locator(':scope > div')
    for (const [index, radius] of ['6px', '10px', '16px', '22px', '9999px'].entries()) {
      await expect(roles.nth(index).locator(':scope > div').first()).toHaveCSS('border-radius', radius)
      await expect(roles.nth(index)).toContainText(radius)
    }
    const experiment = page.getByRole('slider', { name: '自定义圆角' })
    await experiment.focus()
    await experiment.press('End')
    await expect(experiment).toHaveValue('32')
    await expect(roles.first().locator(':scope > div').first()).toHaveCSS('border-radius', '6px')
    await page.screenshot({ path: info.outputPath('shape-language.png'), fullPage: true })
  })
}
