import { test, expect } from '@playwright/test'

for (const width of [640, 1096]) test(`产品体验共享间距 ${width}`, async ({ page }, info) => {
  await page.setViewportSize({ width, height: 704 })
  await page.goto('/')
  await page.getByTestId('primary-sidebar').getByRole('button', { name: 'Playground', exact: true }).click()
  const nav = page.getByTestId('playground-nav')
  await nav.getByRole('button', { name: 'Chat', exact: true }).click()
  const chat = page.getByTestId('surface-baseline-panel')
  const messages = page.getByTestId('chat-surface-scroll')
  const composer = page.getByTestId('chat-surface-composer-area')
  await expect(messages).toHaveCSS('padding-left', '24px')
  await expect(composer).toHaveCSS('padding-left', '24px')
  await chat.evaluate(node => (node as HTMLElement).style.setProperty('--layout-gutter-large', '31px'))
  await expect(messages).toHaveCSS('padding-left', '31px')
  await expect(composer).toHaveCSS('padding-left', '31px')
  await chat.evaluate(node => (node as HTMLElement).style.removeProperty('--layout-gutter-large'))
  await nav.getByRole('button', { name: '设置', exact: true }).click()
  await expect(page.getByTestId('settings-main')).toHaveCSS('padding-left', '24px')
  const card = page.locator('[data-layout-card="settings"]').first()
  await expect(card).toHaveCSS('padding-left', '20px')
  await page.getByTestId('settings-candidate').evaluate(node => (node as HTMLElement).style.setProperty('--layout-card-large', '29px'))
  await expect(card).toHaveCSS('padding-left', '29px')
  await nav.getByRole('button', { name: '人物世界', exact: true }).click()
  await expect(page.getByTestId('moments-content-scroll')).toHaveCSS('padding-left', '16px')
  await page.getByTestId('world-tab-wardrobe').click()
  await expect(page.getByTestId('wardrobe-content-scroll')).toHaveCSS('padding-left', '16px')
  await page.screenshot({ path: info.outputPath('product-spacing.png'), fullPage: true })
  await nav.getByRole('button', { name: '工作区', exact: true }).click()
  const workspaceTabs = page.getByRole('tablist', { name: '工作区功能' })
  await workspaceTabs.getByRole('tab', { name: '终端', exact: true }).click()
  await expect(page.getByTestId('workspace-terminal-output')).toHaveCSS('padding-left', '16px')
  await workspaceTabs.getByRole('tab', { name: '侧边聊天', exact: true }).click()
  await expect(page.getByTestId('workspace-sidechat-messages')).toHaveCSS('padding-left', '16px')
})

for (const theme of ['porcelain-blue', 'yao-stone']) for (const width of [1096, 746]) {
  test(`设计语言布局与透明度 ${theme} ${width}`, async ({ page }, info) => {
    await page.setViewportSize({ width, height: 704 })
    await page.addInitScript(theme => localStorage.setItem('theme', theme), theme)
    await page.goto('/')
    await page.getByTestId('primary-sidebar').getByRole('button', { name: 'Playground', exact: true }).click()
    await page.getByTestId('playground-nav').getByRole('button', { name: '设计语言', exact: true }).click()
    const tabs = page.getByRole('tablist', { name: '设计语言分类' })
    await tabs.getByRole('tab', { name: '布局与间距' }).click()
    const reading = page.getByTestId('layout-reading')
    const densityTabs = page.getByRole('tablist', { name: '布局密度' })
    const scroll = page.getByTestId('layout-scroll-sample')
    await expect(densityTabs.getByRole('tab')).toHaveText(['紧凑', '标准', '宽松'])
    for (const [label, gutter, section] of [['紧凑', 12, 12], ['标准', 16, 20], ['宽松', 24, 24]] as const) {
      await densityTabs.getByRole('tab', { name: label, exact: true }).click()
      await expect(scroll).toHaveCSS('padding-left', `${gutter}px`)
      await expect(reading).toHaveCSS('row-gap', `${section}px`)
      await expect(page.getByTestId('layout-card-sample')).toHaveCSS('padding-left', `${gutter}px`)
    }
    await densityTabs.getByRole('tab', { name: '标准', exact: true }).click()
    const back = page.getByTestId('layout-back')
    expect(Math.abs((await reading.boundingBox())!.x - (await back.boundingBox())!.x)).toBeLessThanOrEqual(2)
    const media = page.getByTestId('layout-media')
    const dimensions = await media.boundingBox()
    await page.getByRole('tab', { name: '加载中', exact: true }).click()
    expect(await media.boundingBox()).toEqual(dimensions)
    await page.getByRole('tab', { name: '加载失败', exact: true }).click()
    expect(await media.boundingBox()).toEqual(dimensions)
    await page.getByRole('button', { name: '长正文', exact: true }).click()
    expect(await page.getByTestId('layout-scroll-sample').evaluate(node => node.scrollHeight > node.clientHeight)).toBe(true)
    const row = page.getByTestId('layout-hover-row')
    await row.scrollIntoViewIfNeeded()
    await page.mouse.move(0, 0)
    const before = await row.boundingBox()
    const action = page.getByTestId('layout-hover-action')
    const actionBefore = await action.boundingBox()
    await row.hover()
    expect(await row.boundingBox()).toEqual(before)
    expect(await action.boundingBox()).toEqual(actionBefore)
    await expect(action).toHaveCSS('opacity', '1')
    await back.click()
    await page.getByRole('button', { name: '查看内容', exact: true }).click()
    await expect(reading).toBeVisible()
    await page.screenshot({ path: info.outputPath('layout.png'), fullPage: true })
    await tabs.getByRole('tab', { name: '透明度', exact: true }).click()
    const surface = page.getByTestId('opacity-surface')
    const initial = await surface.evaluate(node => getComputedStyle(node).backgroundColor)
    const textSurface = page.getByTestId('opacity-text-surface')
    await expect(textSurface).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
    await expect(page.getByRole('heading', { name: '表面透明度', exact: true })).toHaveCount(0)
    await page.getByRole('button', { name: '80%', exact: true }).click()
    await expect(page.locator('output')).toHaveText('80%')
    expect(await surface.evaluate(node => getComputedStyle(node).backgroundColor)).not.toBe(initial)
    await expect(textSurface).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
    await expect(textSurface).toHaveCSS('opacity', '1')
    await page.getByRole('slider', { name: '表面透明度' }).focus()
    await page.keyboard.press('ArrowLeft')
    await expect(page.locator('output')).toHaveText('75%')
    await expect(textSurface).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
    await expect(surface).toHaveCSS('opacity', '1')
    await page.screenshot({ path: info.outputPath('opacity.png'), fullPage: true })
    await page.getByTestId('design-system-panel').evaluate(node => { (node as HTMLElement).style.zoom = '2' })
    expect(await page.getByTestId('design-system-panel').evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    await tabs.getByRole('tab', { name: '透明度', exact: true }).focus()
    await page.keyboard.press('ArrowLeft')
    await expect(tabs.getByRole('tab', { name: '布局与间距' })).toHaveAttribute('aria-selected', 'true')
  })
}
