import { test, expect } from '@playwright/test'

for (const theme of ['porcelain-blue', 'yao-stone']) for (const width of [1166, 600]) {
  test(`OAuth 共享表单候选隔离与固定操作槽 ${theme} ${width}`, async ({ page }, testInfo) => {
    await page.setViewportSize({ width, height: 731 })
    await page.addInitScript(theme => localStorage.setItem('theme', theme), theme)
    await page.goto('/')
    await page.getByTestId('primary-sidebar').getByRole('button', { name: 'Playground', exact: true }).click()
    await page.getByTestId('playground-nav').getByRole('button', { name: '设置', exact: true }).click()
    const candidate = page.getByTestId('settings-surface-candidate')
    await candidate.getByTestId(`settings-candidate-theme-${theme}`).click()
    await candidate.getByRole(width < 640 ? 'tab' : 'button', { name: 'MCP', exact: true }).click()
    const scenes = candidate.getByTestId('settings-candidate-mcp-scenes')
    await scenes.getByRole('tab', { name: '添加连接', exact: true }).click()
    const form = scenes.getByTestId('mcp-connection-form')
    await form.getByLabel('认证方式').selectOption('oauth')
    await expect(form.getByLabel('公共客户端 ID（可选）')).toBeVisible()
    const saved = await page.evaluate(() => JSON.stringify({ ...localStorage }))
    const button = form.getByRole('button', { name: '登录并连接', exact: true })
    await button.scrollIntoViewIfNeeded()
    await page.mouse.move(0, 0)
    const before = await button.boundingBox()
    await button.hover()
    expect(await button.boundingBox()).toEqual(before)
    await page.screenshot({ path: testInfo.outputPath('oauth-form.png') })
    await button.click()
    await expect(form.getByRole('status')).toContainText('已获取 1 个工具')
    expect(await page.evaluate(() => JSON.stringify({ ...localStorage }))).toBe(saved)
    expect(page.context().pages()).toHaveLength(1)
    expect(await form.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
    await scenes.getByRole('tab', { name: '待登录', exact: true }).click()
    const login = scenes.getByRole('button', { name: '登录', exact: true })
    await expect(login).toBeEnabled()
    await login.click()
    await expect(scenes.getByRole('status')).toHaveText('连接中')
    await scenes.getByRole('button', { name: '取消', exact: true }).click()
    await expect(scenes.getByRole('status')).toHaveText('已停用')
  })
}
